Adding first draft of trial interface (Main UI) code to repository
xlai/dosefinderhub pull request #15
Opened 2023-08-23 09:23 UTC by eduardo-vie

This first draft of the code includes 5 tabs, the first being a Mock Configurations tab.
I was in the middle of correcting variable names and overall code aesthetic based on guidelines and updated variable list, so the ui.R code may not run.
This is ultimately regarding issue #4.

2023-08-24 08:00 UTC, xlai requested changes
This is a good draft for our main UI! Like others, my general comments is to reduce the repetitive code to make use of functions and lists. Not only does this make the code cleaner and readable but also make your UI adaptable for the inclusion of more methods.

Things to consider for the next iteration:

1. Modularise your code with purposeful use of functions
2. Consider the use of a database to simplify the input needed for simulation.
3. Coordinate with @jakeholton on the design of visualisation of cross-method comparison.
4. Make first draft of the conduct tab.

2023-08-24 09:02 UTC, jakeholton commented on app/modules/trial_design/ui.R
> +#Variable values are arbitrary since we have not integrated them from the Questionnaire UI yet; I tried to stick to the defaults specified in the spreadsheet
Please make sure you use tpt (instead of 3p3) and lists instead of separate variables (e.g. n_sims$crm instead of n_sims_crm) :)

2023-08-25 12:11 UTC, eduardo-vie commented on app/modules/trial_design/ui.R
> +func_3 <- func_list[ranking[3]]
Thanks for the suggestion, that makes sense.
The way my code is right now, the ranking vector can only have 1, 2 or 3 designs (not more).
Trying to make it more adaptable.

2023-08-25 12:19 UTC, eduardo-vie commented
> This is a good draft for our main UI! Like others, my general comments is to reduce the repetitive code to make use of functions and lists. Not only does this make the code cleaner and readable but also make your UI adaptable for the inclusion of more methods.
> 
> Things to consider for the next iteration:
> 
> 1. Modularise your code with purposeful use of functions
> 2. Consider the use of a database to simplify the input needed for simulation.
> 3. Coordinate with @jakeholton on the design of visualisation of cross-method comparison.
> 4. Make first draft of the conduct tab.

Thanks again for the feedback, it is much appreciated.
I am working on item 4 and will work on 3 soon, hopefully.
I'm still unsure on how to accomplish 1 and 3. Since we're collecting the same method-specific info, @sdennett20 and I can work on a parameter input database together, which should eliminate most repetition in both of our codes, but I don't know what the database or the code would look like. Maybe the three of us can have a chat on Tuesday.

2023-08-25 12:41 UTC, xlai commented on app/modules/trial_design/ui.R
> +
Yes. Once the questionnaire database is set up, you shouldn't have to write these out yourself manually. It should simply take the user profile as the input and output the UI automatically. 

You can wait for the next iteration to modify this section of the code.

2023-08-25 12:42 UTC, xlai commented
> Maybe the three of us can have a chat on Tuesday.

Yes definitely. I hope that we will have the database set up for the generation of dummy data by tuesday.

2023-09-04 12:39 UTC, xlai commented on app/modules/trial_design/ui.R
> +names(func_list) <- c("3p3", "crm", "other")
same here. Please go through all your code to make sure it's coded as `tpt`

2023-09-04 12:52 UTC, xlai approved these changes
This is a generally great update. In the next iteration, I would like to see:

1.  The removal of all dummy variables,
2. The use of generated database from questionnaire UI to streamline the UI and Sever,
3. additional visualisation in the simulation tab, and
4. working version of the conduct tab (if possible).

2023-09-04 12:52 UTC, xlai commented on app/modules/trial_design/ui.R
> +library(ggplot2)
If the package is not being used constantly, try to load each specific function by following our coding guideline (e.g. `packagename::function_name()` )

2023-09-04 13:41 UTC, merged